export const GET_ITEM_LIST_REQUEST = 'GET_ITEM_LIST_REQUEST';
export const GET_ITEM_LIST_FAILED = 'GET_ITEM_LIST_FAILED';
export const GET_ITEM_LIST_SUCCESS = 'GET_ITEM_LIST_SUCCESS';

export const GET_ITEM_INFO_REQUEST = 'GET_ITEM_INFO_REQUEST';
export const GET_ITEM_INFO_FAILED = 'GET_ITEM_INFO_FAILED';
export const GET_ITEM_INFO_SUCCESS = 'GET_ITEM_INFO_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';
